# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InvgateCli < Formula
  desc "Runtime OpenAPI/Swagger CLI — works with any Swagger/OpenAPI spec"
  homepage "https://github.com/wdelcant/invgate-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_macOS_amd64.tar.gz"
      sha256 "057c44240de8306d18e87dacf39e4d3b792394ea0e19c8014b7ff61d19bd52f2"

      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_macOS_arm64.tar.gz"
      sha256 "72bc1158c9ef47350f37b4064d7d0fb78acadb0aac59782a4489da1cc6f174bd"

      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_Linux_amd64.tar.gz"
      sha256 "ff04f3ee31e874c1e824c39b85c2045d890ae796465529999837d64a00650e12"
      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_Linux_arm64.tar.gz"
      sha256 "42bb0352f5d7bb2ed41980c2427b2b610fceeadd338c9c36351493b95fd9327c"
      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
  end

  test do
    system "#{bin}/invgate-cli", "--version"
  end
end
