# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InvgateCli < Formula
  desc "Runtime OpenAPI/Swagger CLI — works with any Swagger/OpenAPI spec"
  homepage "https://github.com/wdelcant/invgate-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_macOS_amd64.tar.gz"
      sha256 "f5e266639e2bf8c65a24573c41a4c37cd0f75d7fe0c5aaa531f806f1bdca6434"

      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_macOS_arm64.tar.gz"
      sha256 "ac03ac0f00e03605a4a1e2f719abb77efa30a319e2e7ea47757057c88a38ee54"

      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_Linux_amd64.tar.gz"
      sha256 "5bc6a45d1bc806cd8551ca089c40649c0035b17a89bb8507faf428d0325913d5"
      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdelcant/invgate-cli/releases/download/v0.1.1/invgate-cli_0.1.1_Linux_arm64.tar.gz"
      sha256 "41fdfd86e68aaecee658834a3735ea1a8383f490643943751f5c7b4e618aed3f"
      define_method(:install) do
        bin.install "invgate-cli"
      end
    end
  end

  test do
    system "#{bin}/invgate-cli", "--version"
  end
end
